[package]
name = "tauri-plugin-extended-fs-scope"
version = "0.0.0"
authors = ["maemon4095"]
description = ""
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.5.*" }
serde = { version = "1.0.*" }
